### ISSUE TITLE
Is there a way to enumerate rendered componets?

### ISSUE THREAD

**Issue by budarin** [developit/preact-router#102]
I need it on server-side to collect critical css.
react-router could do it passing renderProps.components - so I can iterate over components and ask about css resources.

Could it be achieved in preact?

**Comment by developit** [comment]
I've never seen this done. Have an example you can point me to? You could use a hook, if that works.

**Comment by budarin** [comment]
it is in react-router https://github.com/ReactTraining/react-router/blob/master/docs/guides/ServerRendering.md

-> renderProps.components

**Comment by developit** [comment]
Ah, no I would recommend just using react-router itself if you want those features (it works fine via preact-compat). This router is much simpler, and doesn't do anything magical to produce or observe application structure.
