### ISSUE TITLE
A route should accept path with `index.html`

### ISSUE THREAD

**Issue by yfr** [developit/preact-router#103]
Thanks for this easy to use Router. But I think we should have the router also accept index pages. What do you think?

**Comment by developit** [comment]
I've never run into a use-case for this myself - mind giving some insight into why you think it'd be useful?

Normally if I was in a situation where I couldn't enforce pretty index, I'd run something like this synchronously during page load:

```js
if (location.pathname.match(/\/index\.html$/)) {
  history.replaceState(null,null,location.pathname.replace(/index\.html$/, '');
}
```

**Comment by yfr** [comment]
You are right. Normally it shouldn't be any problem. But one of our tools is generating URLs with `index.html` appended per default. I could imagine that there are more of those URLs.

But your snippet sounds like a good workaround for those. You just put this in the head section of your sites?

**Comment by developit** [comment]
I do, yup!  Plus then the URLs are nice and clean :)
You could even use the same technique to generate a meta tag to point search engines to the non-index.html URL.

**Comment by yfr** [comment]
Cool thanks!
