### ISSUE TITLE
Typescript definition file missing from published package (v2.3.2)

### ISSUE THREAD

**Issue by Alexendoo** [developit/preact-router#121]
https://registry.npmjs.org/preact-router/-/preact-router-2.3.2.tgz

There's also a `preact-scroll-viewport` directory in there, doesn't look like it's used

**Comment by developit** [comment]
Yikes, [you're right](https://unpkg.com/preact-router@2.3.2/)! We should switch to a whitelist via package.json `files` array.

**Comment by developit** [comment]
Fixed in `2.4.0`: https://unpkg.com/preact-router@2.4.0/dist/
