### ISSUE TITLE
Path priority issue

### ISSUE THREAD

**Issue by revathskumar** [developit/preact-router#123]
In below routes, the url `/about` will navigate to `<Mail path="/:id"/> ` instead of `<About path="/about" /> `

[Slack Discussion](https://preact.slack.com/archives/general/p1484063570001826) 

```jsx
<Router> 
  <Inbox path="/" default />              
  <About path="/about" />               
  <Mail path="/:id"/>            
</Router>
```
I am trying out fixes as per [this comment](https://preact.slack.com/archives/general/p1484063649001830) But as of now no luck. Will update here is If I made any progress.

**Comment by revathskumar** [comment]
To reproduce, here is the sample repo : https://github.com/revathskumar/react-inbox/tree/master/preact

**Comment by gabrielrtakeda** [comment]
Any progress about this issue? I am facing the same problem..

**Comment by developit** [comment]
Just the referenced PR. Looking into it this week!
