### ISSUE TITLE
Typescript definition missing important properties or has properties that should be optional.

### ISSUE THREAD

**Issue by mseddon** [developit/preact-router#133]
Causes huge walls of (invalid) errors in our codebase after upgrading to 2.4.0.  I've taken to rm'ing `index.d.ts` for now :)

The issues are:

* `Router` has no `history` prop.
* `RouterArgs.matches` should be optional.
* `RouterArgs.url` should be optional.
* `RouterArgs.path` should be present.

I think that's all, but don't have time atm to try to fix or dig deeper so there may be others.

**Comment by developit** [comment]
Yikes! Are you able to do a quick PR to fix those?

**Comment by mseddon** [comment]
not right now :( I can get it at the weekend but atm I am hitting a deadline wall :/

**Comment by mseddon** [comment]
easiest solution would be to remove the typings property from `package.json` until we have a moment to make it sane again :)

**Comment by developit** [comment]
patched in 2.4.1.

**Comment by mseddon** [comment]
Nice!  Will try and get that cleaned up at the end of the week.

**Comment by carmanchris31** [comment]
Any updates on this?

I thought I was losing my mind when my project couldn't find the definition file until I tracked it down to the "x-typings" and then found this issue through the git blame commit hash to disable the typings temporarily. Makes sense now, haha.

**Comment by pspeter3** [comment]
It would be nice to have the type definitions back. I can try and add them.
