### ISSUE TITLE
Programmatical API

### ISSUE THREAD

**Issue by azer** [developit/preact-router#137]
I'm working on a Go framework that needs to combine routing in one JSON document that can be read by both JS and Go. To accomplish this, I can't hard-code the routes, I need an API. 

Is there an example of programmatical usage of preact-router? Documentation seem to not cover such a case.

**Comment by developit** [comment]
Not quite sure I understand - if you mean programmatically triggering a route you can use route():

```js
import { route } from 'preact-router';
route('/foo');
```

**Comment by developit** [comment]
Just re-read - for a routing table you would just use a function to convert your routes to children:

```
import routes from './routes.json';
import pages from './pages'; // map of components

<Router>
  { routes.map( r => (
    <Route {...r} component={pages[r.component]} />
  )) }
<Router>
```

Each entry in the JSON would just have `path`, `component` and any additional props to pass.

**Comment by developit** [comment]
Preact's website actually does this by the way, here the implementation:

https://github.com/developit/preact-www/blob/master/src/components/routes.js

**Comment by azer** [comment]
@developit thanks a lot! I'll share the result with you once I'm done.

**Comment by developit** [comment]
Perfect, that'll make a nice addition to the docs.

**Comment by azer** [comment]
@developit just released it; http://github.com/azer/go-preact-starter

**Comment by developit** [comment]
Awesome, nice work man.
