### ISSUE TITLE
Router fails when serving static bundle 

### ISSUE THREAD

**Issue by daslicht** [developit/preact-router#14]
Hi,
when I deploy a preact bundle to my web-server anythink works fine as long as I start at the root.

eg: www.mydomain/

But if I navigate to a subpath like this:
www.mydomain/profile

I get a 404 ?

How to solve this, please ?

**Comment by rsaccon** [comment]
I guess you are not using a `base` tag in your HTML index file, which defines the path from where your index.html is getting served.

**Comment by daslicht** [comment]
I am using the preact boilerplate : 
https://github.com/developit/preact-boilerplate

This is my code:
https://github.com/daslicht/daslicht-preact_socketio_chat

Live:
http://5.45.104.102

**Comment by rsaccon** [comment]
You have to configure apache with some URL rewriting, so it will always serve http://5.45.104.102/index.html, even if your landing page is http://5.45.104.102/profile or so.

**Comment by daslicht** [comment]
Yeah , the same idea came just to my mind :) and it is working now :)
