### ISSUE TITLE
Link is not compatible with react-router

### ISSUE THREAD

**Issue by rodolfo3** [developit/preact-router#142]
In `react-router`, the target to the `Link` is through the `to` prop:
https://github.com/ReactTraining/react-router/blob/master/modules/Link.js#L51

But in `preact-router`, props are sent directly to `a` tag, requiring the `href` prop to the component:
https://github.com/developit/preact-router/blob/master/src/index.js#L146

Isn't better allow to use the `to` prop?

**Comment by developit** [comment]
preact-router is not a drop-in replacement for React Router. The two accomplish somewhat similar goals, but do so quite differently.  If you are looking for compatibility with React Router, I would strongly recommend using React Router itself, via [preact-compat](https://github.com/developit/preact-compat).
