### ISSUE TITLE
[Question] onEnter, onLeave hooks

### ISSUE THREAD

**Issue by abhishekisnot** [developit/preact-router#143]
I was wondering if [onEnter and onLeave hooks](https://github.com/ReactTraining/react-router/blob/master/docs/guides/ConfirmingNavigation.md) are already supported in preact-router. If not, is it something on a roadmap?

**Comment by developit** [comment]
Nope! You should use lifecycle events, `onEnter` and `onLeave` aren't really necessary.

**Comment by abhishekisnot** [comment]
Thank you. I missed the fact that pages are just components (with URL based conditions).

**Comment by developit** [comment]
No problem! Sorry for being abrupt there, was trying to get through 150 Github notifications in 2 hours. haha

**Comment by abhishekisnot** [comment]
No worries. I can't thank you enough for your work on preact :heart: :heart:
