### ISSUE TITLE
README misleading usage of react-router

### ISSUE THREAD

**Issue by omarchehab98** [developit/preact-router#148]
> **Note:** `preact-router` is simple and does not do orchestration for you. If you're looking for more complex solutions like nested routes and view composition, **[react-router](https://github.com/ReactTraining/react-router) works with preact as long as you alias in [preact-compat](https://github.com/developit/preact-compat).**

I find the last part of this statement very misleading. It is not the case that `react-router` must be aliased with `preact-compat`. I deduced that from the example http://jsfiddle.net/developit/wtpfyfnt. I think it should be rephrased in clearer manner.

Have a great day!

**Comment by developit** [comment]
@omarchehab98 that statement refers to `react-router` v4, which works out of the box with Preact.
