### ISSUE TITLE
Full hash-routing using preact-router

### ISSUE THREAD

**Issue by vineetbaldwa** [developit/preact-router#153]
Let me say first that the current routing implementation works beautifully and I've had no issues, but I have a specific use case where I want to use hashes instead of routes to avoid polluting the javascript history object.

Currently, my main app is setup like this
```
<Router>
  <Index default />
  <UserContainer path='/users' />
</Router>
```

This basic implementation gives me 2 routes:
```www.example.com``` -> which loads my `Index` component
```www.example.com/users``` -> which loads my `UserContainer` component

The issue I'm seeing is that once I go from `/` to `/users`, calling `javascript:history.back()` will take me back to `/` since `/users` is a new route.

I was trying to avoid pushing a new route into my history object, so I thought I could achieve this using hashes for routing instead of full routes.

What I want is
```www.example.com``` -> which loads Index
```www.example.com#users``` -> which loads UserContainer

That way, when i go from `/` to `/users` and call  `javascript:history.back()`, it will take me to what I had before i was on `/` (which is my desired behavior).

Is this possible with preact-router?

**Comment by vineetbaldwa** [comment]
Also I did take a look at #88 and #151 but I don't think its the same use case. Let me know if you feel otherwise

**Comment by developit** [comment]
Mutating `location.hash` actually still adds a history entry.  Perhaps you could use the `replace` option on `route()`:

```js
route('/users', true);   // replaces the current history entry with /users & routes to it
```

**Comment by vineetbaldwa** [comment]
Thanks @developit that is pretty useful. 

Another followup question, is there any way to mutate the javascript history hash using preact-router? I'm asking because my specific use-case involves multiple nested screens, but when an action in the deeply nested screen is successful, I want to return the user to the default page and clear all previous history so that clicking the back button takes you back to where you were before you entered the default page.

**Comment by developit** [comment]
Ah that's a tricky one. I'm not really sure how you'd do that in a way that didn't just involve remembering the history states:

```js
// go back 3 views:
history.go(-3);

// overwrite the original entry with some destination URL:
route('/results', true);
```
