### ISSUE TITLE
Feature: Active class when Link href matches window.location

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/preact-router#171]
I'm currently building a navigation with `preact-router` but I'm stuck with setting an active css class when the `url` matches the `href` prop. The `<Link>`-component doesn't support some sort of active class.

Of course I could switch back to `react-router`, but it seems kinda overkill for my purpose.

**Comment by developit** [comment]
There's a PR in for a basic version that doesn't self-update on route (so it just needs to be contained within something that is rendering in response to the URL) - #150.

I'd like to build a little subscription mechanisms into this lib though that could just publish a message out to all `Link` components telling them to update when the URL changes.

**Comment by developit** [comment]
This was released in [2.5.0](https://github.com/developit/preact-router/releases/tag/2.5.0)! 🎉
