### ISSUE TITLE
TypeScript definition for RouterProps: 'static' is a reserved word

### ISSUE THREAD

**Issue by jmfirth** [developit/preact-router#176]
Was working on creating tests to exercise the TypeScript definitions and ran across this error with the definition for `Router`:

`Identifier expected: 'static' is a reserved word in strict mode.  Modules are automatically in strict mode.`

https://github.com/developit/preact-router/blob/master/src/index.d.ts#L14

Simplest case:
```
<Router static={true}>
```

**Comment by developit** [comment]
Sortof an odd error given it's a JSX property.  We use `default` too, which is also a reserved word.  Maybe it's something to bring up with the TS people?  I just checked, and it looks like Babel intelligently transforms JSX properties to be quoted when they are reserved words:

<img width="613" alt="screen shot 2017-04-17 at 8 25 43 pm" src="https://cloud.githubusercontent.com/assets/105127/25109631/0b201494-23ac-11e7-99cd-5091bc2248b3.png">


https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-0&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=true&spec=false&playground=false&code=%2F**%20%40jsx%20h%20*%2F%0A%0A%3CRouter%20static%3E%0A%20%20%3CFoo%20path%3D%22%2F%22%20default%20%2F%3E%0A%3C%2FRouter%3E

**Comment by jmfirth** [comment]
The more I think about it, more I think this in fact a bug.  If you should not be permitted to use reserved words like that, you shouldn't be able to create a definition as such.  If such a definition is valid you should be able to exercise it.
