### ISSUE TITLE
How to make a async router?

### ISSUE THREAD

**Issue by JonneyYan** [developit/preact-router#18]
Just like react-router, How to make a dynamic router?

This is react-router:

``` javascript
const CourseRoute = {
  path: 'course/:courseId',

  getChildRoutes(location, callback) {
    require.ensure([], function (require) {
      callback(null, [
        require('./routes/Announcements'),
        require('./routes/Assignments'),
        require('./routes/Grades'),
      ])
    })
  },

  getIndexRoute(location, callback) {
    require.ensure([], function (require) {
      callback(null, {
        component: require('./components/Index'),
      })
    })
  },

  getComponents(location, callback) {
    require.ensure([], function (require) {
      callback(null, require('./components/Course'))
    })
  }
}
```

so...Does preat-router have `getCompoents`? or other?

**Comment by developit** [comment]
@JonneyYan Sorry for missing this!  Personally, I use nested components for this, but that doesn't address your need for child routes. Currently the only way to support child routes in `preact-router` is via nesting.

```js
class AsyncRoute extends Component {
  state = {
    component: null
  };

  // when receiving a new path, fetch it asynchronously:
  componentDidReceiveProps({ path }) {
    if (path===this.props.path) return;
    this.getComponents(path, (err, component) => {
      this.setState({ component });
    });
  }

  // user-defined function for fetching and returning the route's Component
  getComponents(location, callback) {
    require.ensure([], function(require) {
      callback(null, require('./components/Course'));
    });
  }

  render(props, { component }) {
    return component ? h(component, props) : null;
  }
}

// usage:
<Router>
  <AsyncRoute path="/course/:courseId" />
</Router>
```

Just a thought. I find async routes a bit awkward, and don't tend to use them. Would be happy to collaborate on a proper solution though, either as part of `preact-router` or a separate lib. :)

**Comment by alexmingoia** [comment]
I suggest instead to expose a static method that receives a URL and returns the matched component. This allows developers to implement their own asynchronous route logic

Implementing async routing in the Router component is a hack, because it requires rendering a blank or empty element until asynchronous matching is complete.

**Comment by developit** [comment]
What happens for async routes that fail to load or don't resolve?

**Comment by alexmingoia** [comment]
It depends on the application. That's why I don't think asynchronous routes in the library are a good idea. But at least if preact-router provides a static route matching method, developers can implement their own async route matching logic.

**Comment by SunnyGurnani** [comment]
Above solution will not work for Isomorphic Data Fetching. renderToString must wait until it has loaded Async Data, wait for re render to happen after state change.

**Comment by developit** [comment]
There are no static (string) rendering libraries that render asynchronously. I'm working on a stateful string renderer that will address this.

**Comment by lohfu** [comment]
@developit i would like to fetch some data from my server to be provided to the different routes/components rendered by the router. is this what an async router entails, or am i looking for different (perhaps already existing) functionality?

**Comment by developit** [comment]
That sounds more like side effecting, typically done using a lifecycle method. Nothing directly to do with routing, just that the router happens to be the component that is rendering your component:

```js
class User extends Component {
  componentDidMount() {
    // the router passes you `url` and any parameters from the matched path
    let name = this.props.name;    // (from "/user/:name")
    let url = '/api/users/' + encodeURIComponent(name);
    fetch(url)                     // make the API call
      .then( r => r.json() )       // parse JSON
      .then( user => {
        this.setState({ user });   // persist into state, triggering a render
      });
  }

  render(props, state) {
    // props.user is from the route path
    // state.user gets populated from our fetch call (initially state is an empty object)
    return (
      <div>
        <h2>Username: {props.user}</h2>
        <p class="profile">{state.user && state.user.profile}</p>
      </div>
    );
  }
}

render((
  <Router>
    <User path="/user/:name" />
  </Router>
), document.body);
```

**Comment by lohfu** [comment]
@developit thanks for the thorough answer! in many situations that does make the most sense, but i have created a pretty unique setup where i think it would actually make sense to have the router handle some data fetching. i will try provide an example shortly.

**Comment by NekR** [comment]
So here is [`preact-async-route`](https://github.com/prateekbh/preact-async-route) repo. Also React Route v4 doesn't have built-in async routes anymore. @developit can we close this?

**Comment by developit** [comment]
Totally, it's even in the readme now.
