### ISSUE TITLE
Callback on route change?

### ISSUE THREAD

**Issue by t47io** [developit/preact-router#182]
Is there a way to have a handler/callback on navigation events of `<Router/>`? Maybe something similar to this: http://strml.viewdocs.io/react-router-component/#user-content-navigation-callbacks

I saw in the code that `<Router/>` has a `prop` named `onChange` (here: https://github.com/developit/preact-router/blob/master/src/index.js#L164), but it does not seem to be used anywhere in the component other than `shouldComponentUpdate`

**Comment by t47io** [comment]
I think a `onChange` or `onNavigation` callback would be great. For example, one may want to update `document.title` for SPA, e.g. https://github.com/gaearon/react-document-title

**Comment by developit** [comment]
onChange should work, I use it for setting `document.title` as you described. It's called here:

https://github.com/developit/preact-router/blob/master/src/index.js#L237,L245

**Comment by guido4000** [comment]
I wonder one thing. How would I propagate this onChange event to a nested component?

**Comment by simevidas** [comment]
@guido4000 I’m not a React/Preact expert, but you could always set it to state, and then pass it down to child components as a prop insider `render()`. Let me know if this is a stupid idea 😅

**Comment by guido4000** [comment]
@simevidas yes, this is how I did it finally. Thank you.
