### ISSUE TITLE
The onClick prop doesn't working in <Link /> component

### ISSUE THREAD

**Issue by gabrielrtakeda** [developit/preact-router#193]
# Description
I have the following component:

```jsx
import { h } from 'preact' /** @jsx h */
import { Link } from 'preact-router'

export default ({ children, href, setActive }) => (
  <Link
    className="components--menu-item"
    href={href}
    onClick={() => {
      console.log('onClick was fired!')
      setActive(false)
    }}
  >
    {children}
  </Link>
)
```

But when I click on the `<Link />`ed button, the `console.log` was not fired.

**Comment by developit** [comment]
Hmm - you're using a fork of `preact-router`.  Was that intentional?  `onClick` works in the current version.

**Comment by gabrielrtakeda** [comment]
Holy God! Actually, I'm using a fork that prioritizes the route. I'll update the fork. Thanks for the quick reply and, sorry for the inconvenience.

**Comment by developit** [comment]
Heh, no problem. I should really merge his PR!

**Comment by gabrielrtakeda** [comment]
Yeah but, one only thing that his route prioritization PR do not cover, was the routes that contain hash. The current prioritization by his PR is:

`/foo`, `/:foo`, `/:foo?`, `/:foo+`, `/:foo*`

It would be great if it has something like:

`/foo`, `/foo?query`, `/foo#hash`, `/:foo`, `/:foo?query`, `/:foo#hash`, `/:foo+`, `/:foo*`

**Comment by developit** [comment]
For sure - seems like that'd be straightforward to add.
