### ISSUE TITLE
Reloading

### ISSUE THREAD

**Issue by azer** [developit/preact-router#194]
Hey there,

I wrote some scripts that reloads the script without refreshing the page. This saves 4 seconds by letting me avoid page refresh, and it's much simpler than HMR. The only thing that gets broken is preact-router, as it's the only module touching the state outside the app. As I understand it's using the history API of the window.

Is it possible to get preact-router somehow reset the state and work after the script re-runs ?

Hope I explained well. This is the script I use to reload the bundle; 

```js
  /*
   * Add up-to-date timestamp to all scripts on the page.
   */
  document.querySelectorAll('script').forEach(script => {
    var rpl = document.createElement('script')
    rpl.src = script.src.replace(/\.js[\?\d]*$/, '.js?' + Date.now())
    script.parentNode.replaceChild(rpl, script)
  })
```

P.S I'm working on this for [go-preact-starter](https://github.com/azer/go-preact-starter)

Thanks!

**Comment by developit** [comment]
What's the artifact of the router breakage? One issue with a simple script replacement is that preact never gets to unmount your old component tree. You might find it useful to do that manually:

```js
var app = document.querySelector('.app')
preact.render(null, app.parentNode, app)
```

I'm thinking the main issue with router would be that it installs history hooks as a side effect of import. We could probably move those to be triggered by the first mount of a router, and removed by the unmount of the last router.

**Comment by azer** [comment]
@developit that code helped me fix the issue! thank you so much.
