### ISSUE TITLE
Example of a redirect route

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact-router#197]
More of a snippet instead of an issue, but for anyone looking for a simple Redirect route (like in react-router) this seem to work great;

```js
import { Component } from 'preact';
import { route } from 'preact-router';

export default class Redirect extends Component {
  componentWillMount() {
  	route(this.props.to);
  }

  render() {
  	return null;
  }
}
```

And you can use it like this;

```js
<Router>
   <Redirect path="/from" to="/to" />
</Router>
```

If @developit  likes the idea, I can add it as a PR to the library 🙃

**Comment by developit** [comment]
Hiya @robinvdvleuten - I love the idea!  Maybe best as a "recipe" of sorts in the README?  There are already a few [here](https://github.com/developit/preact-router#lazy-loading).

**Comment by robinvdvleuten** [comment]
@developit I've created a PR for it (#201)

**Comment by developit** [comment]
Awesome, thanks for setting that up!
