### ISSUE TITLE
Is there a way to pass state with route method?

### ISSUE THREAD

**Issue by marcoroganovic** [developit/preact-router#205]
Hi there,

I guess that title of this issue sums up my question pretty well, but to expand a little bit.
I want to pass state of one component to another which is in this case iframe.

I would like to be able to do this:
```
route("/preview", this.state);
```

I've just started with Preact and probably I'm not doing it inline with communities best practices but still I would love if someone could point me to some resource or technique for resolving this problem.

Thanks!

**Comment by developit** [comment]
Nope - the issue there would be that the URL no longer represents your routing state - that transient object you passed is the real state.  You can serialize the state to a URL querystring (or as JSON), or bypass routing to set the state.

**Comment by marcoroganovic** [comment]
Thanks for the answer! I've done it with querystring, good thing is that I can now share that URL and load preview of page with that configuration, but at the end it feels kinda dirty.

**Comment by searls** [comment]
This is good to close, right Jason?

**Comment by developit** [comment]
Yup!

**Comment by denysonique** [comment]
Navigating with ```window.history.pushState(state, title [, url])``` one may store state within the globally accessible `window.history` object.  
https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

I don't see why this couldn't be implemented in preact-router.
react-router already is utilising this. 
https://reactrouter.com/web/api/history

**Comment by marvinhagemeister** [comment]
@denysonique yup, you can pass the same custom history object to `preact-router` too. See this section in the README: https://github.com/preactjs/preact-router#custom-history
