### ISSUE TITLE
Error thrown on redirect after componentDidMount

### ISSUE THREAD

**Issue by chemzqm** [developit/preact-router#208]
I want to perform redirect if the user is not login, code like this:
``` js
  componentDidMount() {
    let {user} = this.props
    if (!user) return route(`/login`, true)
  }
```
My router config:

``` js
      <Router>
        <Home path="/" />
        <Login path="/" />
      </Router>
``` 
An error would throw on route:
<img width="608" alt="screen shot 2017-07-08 at 9 27 45 pm" src="https://user-images.githubusercontent.com/251450/27985760-5c81aa6a-6424-11e7-83f7-133d4d81d402.png">

I'm using the latest preact and preact-router
``` json
    "preact": "^8.1.0",
    "preact-async-route": "^2.0.0",
    "preact-compat": "^3.16.0",
    "preact-redux": "^2.0.2",
    "preact-router": "^2.5.2",
```
It works well if I wrap the `route(`/login`, true)` with `setTimeout`

**Comment by developit** [comment]
Please try with Preact 8.2.0 as it changed the timing of that lifecycle method.

**Comment by chemzqm** [comment]
No error is thrown with Preact 8.2.0, thanks!
