### ISSUE TITLE
base URL

### ISSUE THREAD

**Issue by laggingreflex** [developit/preact-router#212]
Would be nice to have a base path or root URL option, like this: https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string

<blockquote>

#### `basename: string`

The base URL for all locations. If your app is served from a sub-directory on your server, you’ll want to set this to the sub-directory. A properly formatted basename should have a leading slash, but no trailing slash.

```html
<BrowserRouter basename="/calendar"/>
<Link to="/today"/> // renders <a href="/calendar/today">
```
</blockquote>

**Comment by developit** [comment]
I believe this was working in #100 / #138.
