### ISSUE TITLE
Need support to change url without reloading page

### ISSUE THREAD

**Issue by minaseem** [developit/preact-router#219]
I think `preact-router` works only for `a` tags with `href` attribute. I have scenario where I need to manually trigger the url change,  but that refreshes the page. Can we have anything similar to `this.props.history.push('/foo')` which `react-router` provides.

My scenario is- I have a link  with ripple effect, I need to navigate to different page after the ripple animation is over. I tried doing `location.pathname = "/foo"`, but this reloads the page which I don't want. Is there any existing solution or hack using `preact-router`

**Comment by mitchellhamilton** [comment]
You can use `route`
```jsx
import { route } from 'preact-router'

route('/foo')
```

**Comment by minaseem** [comment]
Worked. Thanks
