### ISSUE TITLE
`matches` property of components overrides global `Element.matches`

### ISSUE THREAD

**Issue by anqurvanillapy** [developit/preact-router#226]
- I was using `swiper.js` and its core library uses `Element.matches` for some selecting mechanism, and `<Match />`'s `matches` property overrides this, raising type error `matches is not a function` that it took me about 1 hr to realize that it was naming pollution
- My solution is wrapping all my components into another big one (before this I used a `<main/>` plain HTML element with `path` property), and giving the top-level component a `path` property for the router and it worked well
- Maybe this issue could be taken into further account, because the stacktrace of naming pollution in some debuggers like DevTools is not that informative

**Comment by developit** [comment]
Hi @anqurvanillapy - definitely a strange error! I think we can have `Router` check if the child it is rendering is an HTML element and avoid passing down any of the URL matches in that case.

**Comment by developit** [comment]
Are you able to provide a sample of the broken JSX?  I'm trying to make sure I covered this case in #231.

**Comment by Ontopic** [comment]
Have a similar problem. When rendering with `preact-render-to-string` produces the following HTML...

`<main><h3>Main</h3><div path="/about" url="/about" matches="[object Object]">About</div></main>`

...when using this input

```
const Main = () => (
  <main>
    <h3>Main</h3>
    <Router>
      <div path="/">Home</div>
      <div path="/about">About</div>
      <div path="/contact">Contact</div>
      <div default>Always</div>
    </Router>
  </main>
)
```
