### ISSUE TITLE
lifecycle issue, componentDidUpdate doesn't fire?

### ISSUE THREAD

**Issue by skaraman** [developit/preact-router#256]
Hey trying to understand how the lifecycle works with the Router, 

basically i have the default template code and I set some other code to run in /home/index.js -> componentDidUpdate()

but it doesn't run when the page is first loaded, I have to navigate away from home to a profile page, then back to home for this event to fire

any insight into the cycle of events when first loading a page with a Router?

**Comment by developit** [comment]
The cycle is the same as for any other component. On first render, only mount lifecycle methods are invoked, not update:

```
// first render
componentWillMount()
render()
componentDidMount()

// subsequent (re-)renders:
shouldComponentUpdate()
componentWillUpdate()
render()
componentDidUpdate()
```

**Comment by skaraman** [comment]
thanks @developit your help and hard work is always appreciated

**Comment by mindplay-dk** [comment]
It would have been nice to have something like `componentDidRender()` for this case - it's pretty confusing and not very elegant, having to duplicate code that should be triggered after every render.

I suppose maybe deviating from React on this point is kind of risky though?
