### ISSUE TITLE
Expose routeTo

### ISSUE THREAD

**Issue by psabharwal123** [developit/preact-router#259]
routeTo function would be helpful if one needs to "forward" instead of "redirect", basically not change the url in the address bar. example use case - default component forwards to /error/404

**Comment by developit** [comment]
It's exposed already:

```js
import { route } from 'preact-router';

route('/page-2')  // appends a history entry

route('/page-3', true)  // replaces the current history entry
```

**Comment by psabharwal123** [comment]
I am asking for 'routeto' not 'route'. Purpose being that i dont want the url in addressbar to change :)

**Comment by studentIvan** [comment]
@psabharwal123 if the pull request for #265 be applied you will able to extend the preact Router class and do what you want to do :)

**Comment by psabharwal123** [comment]
thanks! hopefully someone can review and merge it soon :)

**Comment by psabharwal123** [comment]
@studentIvan please have a look at your changes, one of them breaks minification so cant be merged

**Comment by Davetherave2010** [comment]
I made a PR for this #270 to add this to the docs

**Comment by psabharwal123** [comment]
Thanks but original request was to expose 'routeTo'

**Comment by developit** [comment]
@psabharwal123 if you want to route without changing the URL, use createMemoryHistory from [history](https://www.npmjs.com/package/history).
