### ISSUE TITLE
Any way to access to history object?

### ISSUE THREAD

**Issue by ohpyupi** [developit/preact-router#272]
How can I get access to history object in preact router?

**Comment by developit** [comment]
Since you're passing it into the Router, why not just pass it into Context?

```js
class App extends Component {
  // create your history somewhere
  history = createMemoryHistory();

  getChildContext() {
    return { history: this.history };
  }

  render() {
    return (
      <Router history={this.history}>
        <HomePage path="/" />
        <ErrorPage default />
      </Router>
    );
  }
}

class HomePage {
  componentDidMount() {
    this.context.history  // your history from above
  }
}
```

Alternatively, since history is often a singleton by nature (there's only one address bar in a browser), you could just instantiate your custom history and pass it around using ES Modules or a global.
