### ISSUE TITLE
Please post example of use without transpile

### ISSUE THREAD

**Issue by kristoferjoseph** [developit/preact-router#275]
Tried to get this working by importing Router, Route, and Link, but without using future syntax it would not render.

Have you been able to achieve this? I'd love to see an example if so.

Thank you kindly

**Comment by developit** [comment]
Nothing really specific to Router here:
https://jsfiddle.net/developit/y8s94ajf/

You can see a whole repo of non-transpiled stuff here:
https://github.com/developit/preact-without-babel
