### ISSUE TITLE
Typescript "Duplicate identifier" errors

### ISSUE THREAD

**Issue by lecstor** [developit/preact-router#280]
After adding typescript to my preact-cli app, build has started reporting..
```
[at-loader] Checking finished with 4 errors
✖ ERROR [at-loader] ./node_modules/preact-router/index.d.ts:68:22
    TS2300: Duplicate identifier 'ComponentProps'.
✖ ERROR [at-loader] ./node_modules/preact-router/index.d.ts:69:22
    TS2300: Duplicate identifier 'PreactHTMLAttributes'.
✖ ERROR [at-loader] ./node_modules/preact/dist/preact.d.ts:15:7
    TS2300: Duplicate identifier 'ComponentProps'.
✖ ERROR [at-loader] ./node_modules/preact/dist/preact.d.ts:22:7
    TS2300: Duplicate identifier 'PreactHTMLAttributes'.
Build failed! null
```
after downgrading preact-router from 2.6.0 to 2.5.7 build no longer reports errors.

- I used preact-cli-plugin-typescript to add typescript support
- I found that https://github.com/mike-engel/preact-cli-typescript-sample worked without error until I updated the dependencies.
- I am a verified typescript newb so won't be attempting a fix, but I'm guessing it's this change that is causing the issues.. https://github.com/developit/preact-router/commit/b9327a1c46a4d632b4cf01705b71b6634cbfc581#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8

..happy to be told I'm missing something simple..

**Comment by Alexendoo** [comment]
This one is covered by #274, don't worry it's not an issue on your part. The types for preact changed slightly which preact-router augments, it needs a small change that is not yet released.

I believe we're good to go for a 2.6.1 @developit

**Comment by Alexendoo** [comment]
2.6.1 is now released, updating should fix this for you
