### ISSUE TITLE
How can i go back with history.go(-1)?

### ISSUE THREAD

**Issue by untitledlt** [developit/preact-router#287]
It works but is it safe to use this approach?

**Comment by NicholasPeretti** [comment]
# How can I safely "go back" from a component?

I have a route that can be reachable from multiple part of my app. I'd like to create my component smoothly and render a "go back" button which will redirect the user to the previous page.

I don't use the standard history, I use `memoryHistory` from the package `history`.

What's the best way to do this?

**Comment by marvinhagemeister** [comment]
Closing because the original question has long been answered.

**Comment by alexanderbird** [comment]
> According to the [docs of the history package](https://github.com/ReactTraining/history/blob/master/docs/Navigation.md) you can either call history.go(-1) or history.goBack().

It looks like the URL has changed for the relevant history package docs (.../Navigation.md 404ed for me, but ../navigation.md resolved to documentation about history navigation).

https://github.com/remix-run/history/blob/dev/docs/navigation.md
