### ISSUE TITLE
Support activeClassName of parent link on child route

### ISSUE THREAD

**Issue by thisconnect** [developit/preact-router#288]
```jsx
<Link activeClassName="active" href="/parent">Level 1</Link>
```
Is there any way that the Link's `activeClassName` is active if the route is `/parent/child`, so that the first part of the path matches?

**Comment by thisconnect** [comment]
```
<Link activeClassName="active" path="/parent" href="/parent">Level 1</Link>
```

It is not active in my case if I am on the URI `/parent/something/child`, maybe it is related to `/:code/`?

```
<Router>
    <Foo path="/parent/:code/child" />
```

**Comment by thisconnect** [comment]
I wanted to create a simple demo based on the example but I fail, activeClassName is activeclassname in the dom
http://jsfiddle.net/qc73v9va/329/
Am I doing something wrong or is that not supported in jsfiddle?

**Comment by developit** [comment]
Hi @thisconnect - you're using `Link` from `preact-router`, which is just an `<a>` element with no functionality.  `activeClassName` is only supported on `preact-router/match`:

```js
import { Link } from 'preact-router/match';

<Link activeClassName="active" path="/parent/:code/child">hello</Link>
```

**Comment by thisconnect** [comment]
@developit I just try to recreate the issue in jsfiddle. Is there any wa to import `preact-router/match` ?  doesn't seem to be here https://unpkg.com/preact-router@2.6.1/dist/

**Comment by thisconnect** [comment]
oups found it.. it is not in dist https://unpkg.com/preact-router@2.6.1/match.js

**Comment by thisconnect** [comment]
Ok I did some weird `import()` hack to get Link. Only works in Chrome. http://jsfiddle.net/qc73v9va/353/

Now back to my initial issue: I try to highligh `Profiles` (parent) when the user navigates to a subpage hit goto Jimmy. Is that possible?

**Comment by thisconnect** [comment]
At this point, I propose to remove the question label. Either it is a bug or this feature is not supported.

wontfix?

**Comment by piotrjanosz** [comment]
Hi @thisconnect @developit I use a slightly modified Match component for this.

Instead of comparing the path itself in the render function:

`matches: path === props.path`

 I compare the first part of the url:

``` `/${path.split('/')[1]}` === props.path```

Not sure if it supports all types of urls or it's the most elegant solution though. 

Hope this helps though :)

**Comment by developit** [comment]
I think for this we basically should be recommending `<Match>` instead of the active version of `Link`:

```js
import Match from 'preact-router/match';

const Link = ({ activeClassName, class: c, path, partial, ...props }) => (
  <Match path={path}>
    {({ matches, path: p }) =>
      <a {...props} class={matches || partial && p.startsWith(partial) ? activeClassName : c} />
    }
  </Match>
);
```

**Comment by thisconnect** [comment]
thanks a lot

**Comment by vitorrd** [comment]
> I think for this we basically should be recommending `<Match>` instead of the active version of `Link`:
> 
> ```js
> import Match from 'preact-router/match';
> 
> const Link = ({ activeClassName, class: c, path, partial, ...props }) => (
>   <Match path={path}>
>     {({ matches, path: p }) =>
>       <a {...props} class={matches || partial && p.startsWith(partial) ? activeClassName : c} />
>     }
>   </Match>
> );
> ```
> 
> Usage:
> 
> ```js
> <Link activeClassName="current" partial="/parent">Parent</Link>
> // should show as current for /parent/a/b/c/d
> ```

Hello.

Sorry to revive this topic, but it seems the solution provided is only useful in some cases, e.g. it would fail when the route has a variable in it, wouldn't it?

To that extent, could we have the "exec" function on preact-router exposed so we could actually work around this via reimplementing this functionality?

Thanks!
