### ISSUE TITLE
Route Transitions

### ISSUE THREAD

**Issue by donadley** [developit/preact-router#29]
How would I transition from one route to another after an action is performed? I have seen transitionTo() being used when a RouterContainer is created, but what is the equivalent in preact? I am also looking at securing a route until someone logs in. I have seen the following for React, is there also an equivalent for the following? 
```
static willTransitionTo(transition, params, query, callback) {
		if (!AuthStore.loggedIn()) {
			// go over to login page
			transition.redirect('/login', null, {
				redirect: transition.path
			});
```

**Comment by developit** [comment]
To redirect, you can use the `route()` method.  The static `willTransitionTo` method from react-router is a little awkward (I believe they are looking at alternative ways to implement such things).  My suggestion would be to use a high-order component that does the session check and conditionally renders the _actual_ route component only if there is a valid session.

Here's a simple example:

```js
import { route } from 'preact-router';

const AuthenticatedRoute = ({ route }) => {
  if (!AuthStore.loggedIn()) {
    // redirect to login:
    setTimeout( () => route('/login'), 1);
    // don't render the route:
    return null;
  }
  // we're logged in, so render the route:
  return route;
}
```

> You could also do the `loggedIn()` check asynchronously by firing it from `componentDidMount()` and setting the returned Boolean as a property in a stateful component.

---

Here's a more complete example, using a generalized `<AuthenticatedRoute />` high order component to wrap a given route in an auth check like you described:

```js
import { Router, route } from 'preact-router';

class AuthenticatedRoute extends Component {
  componentWillMount() {
    let { check, login } = this.props;
    this.allowed = check();
    if (!this.allowed) route(login || '/');
  }
  render({ check, login, route:Route, ...props }) {
    return <div>{ this.allowed && <Route {...props} /> }</div>;
  }
}

const LoginRoute = () => <form>login form here</form>;

const AccountRoute = () => <div>secret account page</div>;

const Demo = () => (
  <Router>
    <LoginRoute path="/login" default />
    <AuthenticatedRoute
      path="/account"
      login="/login"
      check={AuthStore.loggedIn}
      route={AccountRoute} />
  </Router>
);
```

**Comment by donadley** [comment]
I am using Browserify to embed this application into a overlaying application. When I used the route method the url root changes to /account. So http://www.domain.com to /account. The default tag works here when the application first loads but how can I navigate to /account or any other component?

**Comment by developit** [comment]
@donadley I can't believe I forgot to reply to this, sorry!  I actually did end up finding and fixing a bug relating to your `/account` only working the first time.  It had to do with High Order Components (the router is one) being incorrectly unmounted in some scenarios, which had the effect of disabling URL handling.  Try the latest beta (5.0.0-beta6): `npm install --save preact@beta`, which should fix the issue.

**Comment by donadley** [comment]
Hey, thanks for fixing the issue.

**Comment by ethanroday** [comment]
@developit Thanks for this example. What's the recommended pattern for redirecting back to the protected path once login completes? Currently just using `history.back()` but that seems rather hacky.

**Comment by ethanroday** [comment]
@developit Thanks for the example. What's the recommended pattern for redirecting back to the authorized component after login? Right now I'm just using `history.back()`, but that seems pretty hacky.

**Comment by developit** [comment]
I'd recommend using `route('/login', true)`, or store the previous route using a `<Router onChange={..}>` handler.
