### ISSUE TITLE
Programatic routing hide parameters

### ISSUE THREAD

**Issue by gopalramadugu** [developit/preact-router#295]
Is there a way to hide parameters I am passing to the next page ? There are situations where you would want to hide some information. Trying to see if this is possible. I am referring to the programatic routing using route function.

**Comment by developit** [comment]
Preact Router doesn't allow this because it breaks URLs. I would suggest putting the information into `sessionStorage`, a global variable, context, or centralized state container like `redux` or `unistore`.
