### ISSUE TITLE
Match never called if path doesn't match

### ISSUE THREAD

**Issue by SleeplessByte** [developit/preact-router#296]
Version: 2.6.1

Taken from the example:
```jsx
<Router>
  <Match path="/">
    { ({ matches, path, url }) => (
      <pre>{url}</pre>
    ) }
  </Match>
</Router>
```

This only renders anything at the root (`/`) or whatever value `path` is. I need to change this to:

```jsx
<Router>
  <Match path="/" default={true}>
    { ({ matches, path, url }) => (
      <pre>{url}</pre>
    ) }
  </Match>
</Router>
```

... to make this work.

**Comment by developit** [comment]
`Match` can't be a child of `Router` - Router interprets `path="/"`.

**Comment by SleeplessByte** [comment]
I just re-read the documentation and I don't think that's very clear (neither things you've mentioned). I understand that composition with `preact-router` isn't possible like `react-router` and `reach-router`.
