### ISSUE TITLE
Support Hashtag Urls

### ISSUE THREAD

**Issue by schmitch** [developit/preact-router#3]
It would be great if you also have a way to have Hashtag urls i.e instead of:

    http://developit.github.io/
    http://developit.github.io/active
    http://developit.github.io/completed

it should be:

    http://developit.github.io/#/
    http://developit.github.io/#/active
    http://developit.github.io/#/completed

I mean currently we have some companies where we develop some apps and their browsers won't work nicely with these native urls.

**Comment by developit** [comment]
I'm definitely open to adding this, as a fallback when pushState is not available. Just need to make sure didn't add bloat, but it should be an issue.
