### ISSUE TITLE
Notice: preact-router 3.0.0 is not compatible to current stable preact 8.4.2

### ISSUE THREAD

**Issue by hbroer** [developit/preact-router#301]
preact-router version 3.0.0 is not compatible to preact 8.4.2 because toChildArray does not exist in preact. This will be fixed with 10.x.x i guess, but i can't use the alpha because of many other errors and warnings then.

File: src/index.js
```javascript
import { cloneElement, createElement, Component, toChildArray } from 'preact';
```
i spend a while until i realize that this versions are not compatible. preact-router 2.6.1 is working with preact 8.4.2

**Comment by marvinhagemeister** [comment]
@developit sounds like we should tag the 2.x as `latest`and 3.x as `next` like we did with `preact-render-to-string`👍

**Comment by marvinhagemeister** [comment]
Just updated the tags on npm. `2.6.1` points to `latest` again and `3.0.0` can be installed via `preact-router@next` :tada: :+1:
