### ISSUE TITLE
怎么设置返回上一层不刷新数据 保留之前的

### ISSUE THREAD

**Issue by thisSillyCow** [developit/preact-router#314]

**Comment by marvinhagemeister** [comment]
Closing, it's impossible to help without any description in English. Putting the title through Google Translate returns gibberish:

```txt
How to set back to the previous layer without refreshing the data before the reservation
```

@thisSillyCow Please post a detailed description of the issue you're running into or the question you have (in English). That way users can help you out a lot easier :slightly_smiling_face:
