### ISSUE TITLE
Router Component Does Not Stay on "/" Path When Navigating with `route` Function

### ISSUE THREAD

**Issue by MTtankkeo** [developit/preact-router#473]
# Description
It seems that when the Router component is consistently set with the "/" path, it is expected to remain on this route. However, when navigating to a different route using the route function, the Router component does not stay at "/" but instead transitions to the specified route.

This behavior appears inconsistent because the Router component functions correctly when the route function is not used. Additionally, the page renders as expected at the "/" path upon reloading. I tested a similar scenario with React Router, and the Router component in React maintained the "/" path as expected during navigation. This suggests that the behavior observed with the current Router component may differ from what is anticipated.

Could this be a potential issue, or is there an intended design that explains this behavior?

# Reproducible Code
```tsx
import Router, { route, Route } from "preact-router";

export function App() {
    return (
        <Router url="/">
            <Route path="/a" component={A} default />
            <Route path="/b" component={B} />
        </Router>
    )
}

export function A() {
    return (
        <button onClick={() => route("/b")}>go A</button>
    )
}

export function B() {
    return (
        <button onClick={() => route("/a")}>go B</button>
    )
}
```

If this is intended behavior, it might be beneficial to rename the property from url to initialUrl for clarity. Thank you.

**Comment by rschristian** [comment]
Hey,

In case you missed it in the ReadMe, `preact-router` is no longer maintained & issues will not be addressed. We recommend `preact-iso` in its place.

For what it's worth though, the `url` prop is meant for SSR -- you shouldn't really be setting it on the client.

**Comment by MTtankkeo** [comment]
Sorry, I didn't realize that preact-iso existed. Thanks for letting me know. I wasn't aware that preact-router is no longer maintained. Haha. :D

**Comment by rschristian** [comment]
You can still use `preact-router`, no need to immediately migrate necessarily. It's stable after all.
