### ISSUE TITLE
Calling route() synchronously during routing fails

### ISSUE THREAD

**Issue by idchlife** [developit/preact-router#48]
This is part of the code that uses ::route from Router:

![image](https://cloud.githubusercontent.com/assets/4563032/16458578/36b06eca-3e28-11e6-8ac3-5de814317f95.png)

Main render occurs and then in 1 second ::route used to route back to index (in my case when user is not authenticated), but when clicking back and back something bad happens when everything becomes broken and empty:

https://monosnap.com/file/OMP8Vx9llMUzekylnHG78TXvONDhfS

**Comment by developit** [comment]
Hi @idchlife - thanks for the screen cap, that helps.  Just so I know, which version of preact is this with?  There was an issue very similar to this (possibly the same?) in preact 4.8.0 when used with preact-router, and it's fixed in the preact beta.

**Comment by developit** [comment]
Other fix noted here (with a follow-up): https://github.com/developit/preact/issues/190#issuecomment-225618792

**Comment by idchlife** [comment]
"preact": "^5.1.0-beta.19",
"preact-router": "^2.0.0",

**Comment by developit** [comment]
Does wrapping the `route('/')` call in a setTimeout (temporarily) fix the issue?

```js
setTimeout( () => route('/') );
```

**Comment by idchlife** [comment]
Yes it does! 😱

**Comment by developit** [comment]
Perfect. Obviously that's a hack, so I'll put some safeguards around `route()` to deal with a redirection.

**Comment by developit** [comment]
Fixed in [2.3.0](https://github.com/developit/preact-router/releases/tag/2.3.0)!
