### ISSUE TITLE
NPM distribution for 1.2.0 not pulling in utils.js

### ISSUE THREAD

**Issue by billneff79** [developit/preact-router#5]
The new package in npm doesn't appear to have properly bundled in the newly factored out utils.js class.  I get this when trying to use the new 1.2.0 package in my project

````
ERROR in ./~/preact-router/dist/preact-router.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./util in /Users/bneff/repos/push-notification-pub-tool/node_modules/preact-router/dist
 @ ./~/preact-router/dist/preact-router.js 1:73-118
````

**Comment by developit** [comment]
Apologies, the build was supposed to get switched to rollup to bundle that file and didn't.
Fix was just released in `1.2.1`.
