### ISSUE TITLE
After preact project build,router failed.

### ISSUE THREAD

**Issue by Obooman** [developit/preact-router#61]
I use react-router as I cloned [preact-boilerplate](https://github.com/mxstbr/react-boilerplate/) and develop with all it's dependencies .After my development I release it with `npm run build` and I get html/style/bundle files.Then I host them with `nginx` and give it a server name `preact.demo.com`,I can access `http://preat.demo.com` but I cant access `preact.demo.com/route-one` while I can view it(`http://localhost:PORT/route-one`) when the webpack develop server is on.Any usage mistacks?

**Comment by developit** [comment]
Hi @Obooman - in order to use the HTML5 history API (what Router uses), you need to add a small bit of configuration to your NGINX:

```
location / {
    root /path/to/app;
    try_files $uri index.html;
}
```

More details here:
http://stackoverflow.com/a/28886464/194340

**Comment by Obooman** [comment]
Thanks @developit
