### ISSUE TITLE
Nested Routes

### ISSUE THREAD

**Issue by FallingSnow** [developit/preact-router#95]
Sorry, I'm very new to react and haven't been able to get nested routes working. Could you possibly tell me what I'm doing wrong. I forked your real world example.

I can't seem to load the child view.

https://jsfiddle.net/uwd4x6xx/1/

**Comment by NicolasParada** [comment]
```jsx
const App = () => (
  <div class="app">
    <Header />
    <Router>
      <Root path="/">
        <Router>
          <Home path="/" />
          <Profile path="/profile/:user?" />
        </Router>
      </Root>
      <Error type="404" default />
    </Router>
  </div>
);
```
And there is no IndexRoute component.

**Comment by developit** [comment]
Yup. I'd like to add an optional `path` prop for `<Router>` that lets you define the base path.

**Comment by FallingSnow** [comment]
I see. Seems kind of complex to use nested routes in preact. I think I'll use react for the time being.

Thank you for responding.

**Comment by developit** [comment]
@FallingSnow `preact-router` is just a simple router, if you want nesting just use react-router - it works fine with Preact.

**Comment by FallingSnow** [comment]
Oh. Dang, I already switched. Might switch back then.

On a side note, I remember seeing a test where preact performed better than react. Is that true or is preact only a smaller react?

**Comment by developit** [comment]
@FallingSnow heavily dependent on the test, but in general Preact is faster. It's doing less work, and is the result of hundreds (thousands?) of hours of optimization. Preact also only re-renders from the point of change (the component you called `setState()` on), recycles DOM elements and Components, and batches DOM updates (you can even configure how it does the batching, like tell it to use `requestAnimationFrame`).

The new homepage of [preactjs.com](https://preactjs.com) includes a bunch more of these details, just released it on Monday:
<img width="981" alt="screen shot 2016-11-23 at 2 05 37 pm" src="https://cloud.githubusercontent.com/assets/105127/20575127/faf630dc-b185-11e6-9151-00a94b6c8cb6.png">

**Comment by FallingSnow** [comment]
Not sure if you know but the links on the preactjs.com website, like [customizable update batching](https://preactjs.com/guide/configuration#debounceRendering), are broken links.

**Comment by developit** [comment]
heh - yeah someone pointed that out in Gitter yesterday. I had meant to add the configuration guide before publishing, got a little bit ahead of myself! haha

**Comment by FallingSnow** [comment]
Ok. Good to know that preact generally has better performance. Will most likely switch back.

**Comment by indatawetrust** [comment]
[It works nicely.](https://jsfiddle.net/indatawetrust/evf29dzm/) thank you developit!
