### ISSUE TITLE
Code Splitting Example 

### ISSUE THREAD

**Issue by Vani-gurnani** [developit/preact-router#96]
Since preact is all about smaller Java Script it would be great if you can provide functionality to support Code Split for preact-router

**Comment by developit** [comment]
It's unlikely to be a feature of `preact-router` itself, but I'd be happy to provide examples and recommended ways to do this.  The simplest way is to use a compositional component like [`<SplitPoint />`](https://gist.github.com/developit/9f547d32b96f879b259be399a5dc0f01) as a child of the router:

```js
<Router>
  <SplitPoint path="/" load={require('bundle?lazy!./home')} />
  <SplitPoint path="/user" load={require('bundle?lazy!./users')} />
  <SplitPoint path="/users/:user" load={require('bundle?lazy!./users/user')} />
  <SplitPoint default load={require('bundle?lazy!./not-found')} />
</Router>
```

**Comment by Vani-gurnani** [comment]
Thanks does preact-router support server side rendering ?

**Comment by developit** [comment]
yup! you can pass any URL to the router and it will render the correct children accordingly:

```js
import { h } from 'preact';
import renderToString from 'preact-render-to-string';

/*
// assuming you have an app defined like this:
const MyApp = ({ url }) => (
  <Router url={url}>
    <Home path="/" />
  </Router>
);
*/

// example: express
app.get( (req, res) => {
  let html = renderToString(h(MyApp, { url: req.url }));
  res.send(html);
});
```

**Comment by Vani-gurnani** [comment]
I really liked preact-boilerplate is there a version of that with
code-split and server side rendering ?

That would be perfect for starting production quality apps with preact

**Comment by developit** [comment]
There isn't one yet, but that sounds like a good idea!  I don't do much server rendering since I like to deploy all my stuff to a CDN, but there are lots of people who want it.  Perhaps a clone of preact-boilerplate that does SSR and shows how Code Splitting works would be ideal.  The code splitting could be in both, really.

**Comment by Vani-gurnani** [comment]
Ya only reason for SSR is to support SEO

Most people like me hate webpack it too much mess to set it up right
specially for isomorphic apps

I will try to do this and will let you know if I need help

**Comment by MatteoWebDesigner** [comment]
@developit I was trying to add code splitting too for js and css too.

**Comment by developit** [comment]
Code splitting for CSS is super tricky. I'm not aware of any great ways of doing that with Webpack currently.  Usually you have to decide between loading all your CSS at once, or loading initial CSS but pushing less-used CSS into your lazy-loaded JavaScript modules.

**Comment by MatteoWebDesigner** [comment]
It's because the the css order issue?

**Comment by developit** [comment]
No, I just don't know of an existing way of doing it cleanly.  I guess the underlying reason would be that typically external stylesheets are created via ExtractTextPlugin in Webpack, and that plugin only supports extracting to a single external stylesheet.

**Comment by prateekbh** [comment]
Code splitting can be easily done once #135 is resolved.

**Comment by prateekbh** [comment]
for code splitting please and lazyloading components please visit
https://github.com/prateekbh/preact-async-route

can we close the issue @developit

**Comment by developit** [comment]
Yup yup! Happy to close now that we have a great lib for this :)
