### ISSUE TITLE
Question : Auto wire of HTML links

### ISSUE THREAD

**Issue by Wykks** [developit/preact-router#97]
If link are added with somethings like innerHTML or dangerouslySetInnerHTML , the links are not working because of `isPreactElement(t)` (and that makes sense).
https://github.com/developit/preact-router/blob/master/src/index.js#L117

I use `dangerouslySetInnerHTML` for translated content which can use `<a>` inside.
How should I handle these links ?

Thanks ! :)

**Comment by developit** [comment]
Hi there! You're right, this makes that impossible.  I'd like to support your use-case though.  I think we need to add a global option for "wire all links" and make that the default.  It seems cleaner than checking if an element was created by Preact.

**Comment by Wykks** [comment]
Woa actually preact-markup fit perfectly for my use case ! :+1: 

I don't know if a global options for "wire all links" would be necessary since preact-markup seems to be the way to go.

**Comment by developit** [comment]
Awesome! Plus now all your HTML is pluggable. You can embed preact components into it using custom elements! :)
